#!/usr/bin/env bash

me=$(readlink -f "$0")
me2=$(which "$0")
exe=$(which -a asciidoctor | grep -v "$me" | grep -v "$me2" | head -n1)
ext=$HOME/.config/asciidoctor/extensions

if ! [[ -d "$ext" ]]; then
    exec $exe "$@"
else
    ARGS=()
    while (($#)); do
        case "$1" in
            -r|--require)
                e=$2; shift
                lib=$(readlink -f "$ext/${e%.rb}.rb")
                [[ ! -f "$lib" ]] && lib=$e
                ARGS+=( "-r" "$lib" )
                ;;
            *) ARGS+=( "$1" );;
        esac
        shift
    done
    set -- "${ARGS[@]}"
    #exec $exe "$@"
    exec ruby2.4 $exe "$@"
fi
