#!/usr/bin/env bash

#exec asciidoctor -r /home/c82tber/src/vcs/asciidoctor-pdf/lib/asciidoctor-pdf.rb -b pdf "$@"
#exec /home/c82tber/src/vcs/asciidoctor-pdf/bin/asciidoctor-pdf "$@"

bin_root=/home/c82tber/src/vcs/text/asciidoctor/asciidoctor-pdf/

exts=( "$HOME/.config/asciidoctor/extensions" "$HOME/.config/asciidoctor-pdf/extensions" )

ARGS=()
while (($#)); do
    case $1 in
        -r|--require)
            e=$2; shift
            for ext in ${exts[@]}; do
                lib=$(readlink -f "$ext/${e%.rb}.rb")
                [[ -f "$lib" ]] && break
            done
            [[ ! -f "$lib" ]] && lib=$e
            ARGS+=( "-r" "$lib" )
            ;;
        *) ARGS+=( "$1" );;
    esac
    shift
done
set -- "${ARGS[@]}"
exec ruby2.3 "${bin_root%/}"/bin/asciidoctor-pdf "$@"
