#!/usr/bin/env bash

base=$(dirname "$(readlink -f "$0")")
! [[ -f "$base/asciidoctor" ]] && "Configuration error: can't find asciidoctor library" && exit 1

__as_lib=1
. "$base/asciidoctor"
__as_lib=0

asciidoctor=
config_dir="$HOME/.config/asciidoctor-pdf"
config="$config_dir/config"
! find_exe "asciidoctor-pdf" && echo "ERROR: asciidoctor-pdf found neither in config nor PATH." && exit 1

exts+=( "$HOME/$config_dir/extensions" )

parse_args "$@"
set -- "${ARGS[@]}"

((DEBUG>1)) && exec echo "$asciidoctor" "$@"
exec "$asciidoctor" "$@"
